spring.application.name=auth-service
server.port=7171

#Aplication Context Path while running embedded server
server.servlet.context-path=/e-commerce-authService

#MySQL Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Auth-Service-Databese
spring.datasource.username=root
spring.datasource.password=Vishal@2141
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.keepalive-time=100000


# JPA-Hibernate Entries for MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


# JWT Secret Key (must be at least 32 characters for HS256)
jwt.secret=MySuperSecretKeyForJwtTokenThatIsVerySecure12345

# JWT Expiration Time in milliseconds (1 hours = 3600000 ms)
jwt.expiration=3600000




